# Generated by Django 5.2.12 on 2026-03-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allowed_priorities',
            field=models.JSONField(blank=True, default=list, help_text='Priority levels, e.g., ["critical", "high", "medium", "low"]'),
        ),
        migrations.AddField(
            model_name='organization',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text='Roles in this org, e.g., ["admin", "manager", "developer", "qa"]'),
        ),
        migrations.AddField(
            model_name='organization',
            name='allowed_task_types',
            field=models.JSONField(blank=True, default=list, help_text='Task types, e.g., ["bug", "feature", "story", "spike"]'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text="URL-friendly name, e.g., 'infosys'", unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(default='medium', help_text='Priority defined by organization config', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(default='task', help_text='Task type defined by organization config', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='engineer', help_text='Role defined by organization config', max_length=50),
        ),
    ]
